#include "servo.h"

#define SERVO_PWM_TIM_HANDLE htim4
#define SERVO_PWM_TIM_CHANNEL TIM_CHANNEL_3
#define SERVO_MAX_PULSE 250
#define SERVO_MIN_PULSE 50

void Servo_Init(){
    HAL_TIM_PWM_Start(&SERVO_PWM_TIM_HANDLE,SERVO_PWM_TIM_CHANNEL);
    __HAL_TIM_SET_COMPARE(&SERVO_PWM_TIM_HANDLE,SERVO_PWM_TIM_CHANNEL,(SERVO_MAX_PULSE+SERVO_MIN_PULSE)/2);
}

void Servo_SetAngle(uint8_t angle){
    uint8_t pulse = ((SERVO_MAX_PULSE-SERVO_MIN_PULSE)*angle)/180+50;
    __HAL_TIM_SET_COMPARE(&SERVO_PWM_TIM_HANDLE,SERVO_PWM_TIM_CHANNEL,pulse);
}